# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
