# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20160805_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
